import { Router } from 'express';
import { authRoutes } from './auth.routes.js';
import { userRoutes } from './user.routes.js';
import { professionalRoutes } from './professional.routes.js';
import { clinicRoutes } from './clinic.routes.js';
import { registryRoutes } from './registry.routes.js';
import { specialtyRoutes } from './specialty.routes.js';
import { categoryRoutes } from './category.routes.js';
import { tagRoutes } from './tag.routes.js';
import { paymentTypeRoutes } from './paymentType.routes.js';
import { debitCardRoutes } from './debitCard.routes.js';
import { creditCardRoutes } from './creditCard.routes.js';
import { dependentRoutes } from './dependent.routes.js';
import { addressTypeRoutes } from './addressType.routes.js';
import { addressUserRoutes } from './addressUser.routes.js';
import { professionalReviewRoutes } from './professionalReview.routes.js';
import { clinicReviewRoutes } from './clinicReview.routes.js';
import { professionalRegistryRoutes } from './professionalRegistry.routes.js';
import { professionalSpecialtyRoutes } from './professionalSpecialty.routes.js';
import { professionalClinicPartnersRoutes } from './professionalClinicPartners.routes.js';
import { serviceRoutes } from './service.routes.js';
import { serviceTagRoutes } from './serviceTag.routes.js';
import { saleRoutes } from './sale.routes.js';
import { authMiddleware } from '../middlewares/auth.middleware.js';

const router = Router();

router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/professionals', professionalRoutes);
router.use('/clinics', clinicRoutes);
router.use('/registries', authMiddleware, registryRoutes);
router.use('/specialties', authMiddleware, specialtyRoutes);
router.use('/categories', authMiddleware, categoryRoutes);
router.use('/tags', authMiddleware, tagRoutes);
router.use('/payment-types', authMiddleware, paymentTypeRoutes);
router.use('/debit-cards', authMiddleware, debitCardRoutes);
router.use('/credit-cards', authMiddleware, creditCardRoutes);
router.use('/dependents', authMiddleware, dependentRoutes);
router.use('/address-types', authMiddleware, addressTypeRoutes);
router.use('/address-users', authMiddleware, addressUserRoutes);
router.use('/professional-reviews', authMiddleware, professionalReviewRoutes);
router.use('/clinic-reviews', authMiddleware, clinicReviewRoutes);
router.use('/professional-registries', authMiddleware, professionalRegistryRoutes);
router.use('/professionalSpecialties', authMiddleware, professionalSpecialtyRoutes);
router.use('/partners', authMiddleware, professionalClinicPartnersRoutes);
router.use('/services', authMiddleware, serviceRoutes);
router.use('/service-tags', authMiddleware, serviceTagRoutes);
router.use('/sales', authMiddleware, saleRoutes);

export { router };